### ISSUE TITLE
Wifi scan error

### ISSUE THREAD

**Issue by jaksatomovic** [ESP32-Web/WiFi-Manager_Library#2]
I have adafruits feather esp32-s3 nopsram board and when i open local site and press scan for wifi esp32 fauls and restarts itself

**Comment by FarazFKhan** [comment]
I had this issue happening in the early stages of this library being made. After a few changes this issue had disappeared on my end, but I think my solution was limited to certain conditions. I will revisit that and attempt to patch this bug up once I get the chance to do so. Will post an update once a patch has been committed to Github.

**Comment by FarazFKhan** [comment]
> I have adafruits feather esp32-s3 nopsram board and when i open local site and press scan for wifi esp32 fauls and restarts itself

Just a quick update: The issue has been fixed. Just need to refactor some code, clean it up. I will commit the changes by the end of week if not sooner. I just hope this fix works on all ESP32 boards as I was only able to test on 2 variants I have right now.

**Comment by FarazFKhan** [comment]
> Also one note. I had to change following code in order for LittleFS to work with S3 chip
> 
> ```
>      // if (!LittleFS.begin(FORMAT_LITTLEFS_IF_FAILED)) {
>     if (!LittleFS.begin(FORMAT_LITTLEFS_IF_FAILED, "/littlefs", 10, "ffat")) { // this is used on esp32-s3
> 	Serial.println("LittleFS Mount Failed");
> 	return;
>      }
> ```

Interesting, thank you for pointing that out. I will order a ESP32-S3 so I can run tests on that as well.

**Comment by FarazFKhan** [comment]
> > I have adafruits feather esp32-s3 nopsram board and when i open local site and press scan for wifi esp32 fauls and restarts itself
> 
> Just a quick update: The issue has been fixed. Just need to refactor some code, clean it up. I will commit the changes by the end of week if not sooner. I just hope this fix works on all ESP32 boards as I was only able to test on 2 variants I have right now.

This update has been pushed. You can download the updated files from the ESP32 Web website or from github directly. Licencing requirements have also been removed.

**Comment by jaksatomovic** [comment]
Thank you 👍

**Comment by jaksatomovic** [comment]
quick update - it works now!
