### ISSUE TITLE
Open web page automaticaly after connecting to AP

### ISSUE THREAD

**Issue by jaksatomovic** [ESP32-Web/WiFi-Manager_Library#4]
Is there a way how to achive this? :)

**Comment by FarazFKhan** [comment]
Ahh, interesting. No, not currently. But I can have a look into this at some point this coming week and assess if it can be implemented easily.

**Comment by FarazFKhan** [comment]
I looked into it & this feature can be added relatively easily. Have tested on ios (screenshot below), but still need to test on android before pushing the update. Will update this thread once the update has been pushed.

![WhatsApp Image 2024-02-13 at 21 20 41_01224286](https://github.com/ESP32-Web/WiFi-Manager_Library/assets/67421013/0a59e6e9-2abe-4efd-821b-22a2c7aa7d0b)

**Comment by jaksatomovic** [comment]
Great news! Thx

**Comment by FarazFKhan** [comment]
Have commited the update for the Captive Web Portal. This can now be turned on or off based on the user case. If the boolean "captiveWebPortal" is set to:

- **true :** Activates Captive Web Portal
- **false :** Deactivates Captive Web Portal

 
![image](https://github.com/ESP32-Web/WiFi-Manager_Library/assets/67421013/04173b4c-3515-411e-8ba4-31e1b27671f6)


Let me know if anyone runs into any issues.

**Comment by jaksatomovic** [comment]
Amazing. Thx
