### ISSUE TITLE
[  4228][E][vfs_api.cpp:105] open(): /littlefs/wifi-config.json does not exist, no permits for creation

### ISSUE THREAD

**Issue by HerculesSP** [ESP32-Web/WiFi-Manager_Library#9]
Sorry my bad english, I speak portuguese.

Whenever the code is uploaded to the esp32, the problems shown in the first image appear, immediately after connecting to the AP, the errors shown in the other images appear

version 0.1.2

plataformIO (vscode) Core 6.1.14·Home 3.4.4

esp32s3 n16r8

![erro1](https://github.com/ESP32-Web/WiFi-Manager_Library/assets/76433533/d4f781f0-328a-4f7f-9139-fc7f4f4c5ec5)
![erro2](https://github.com/ESP32-Web/WiFi-Manager_Library/assets/76433533/1fcff842-20c9-4738-ab1b-804d260d2991)
![erro3](https://github.com/ESP32-Web/WiFi-Manager_Library/assets/76433533/601edb9a-20b6-450f-8618-7fad5afbf983)

**Comment by FarazFKhan** [comment]
Hello there, apologies for the delay in getitng back to you - had been away for a while. Are you still having this issue or has it been resolved?

**Comment by FarazFKhan** [comment]
Closing this as I've not yet heard back.
